// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkH0yYc0B09J90OZcCVCZo8-5sQKancHE',
    appId: '1:996364339289:web:5ba0d4e8aa5ae991c40948',
    messagingSenderId: '996364339289',
    projectId: 'myinvestmentapp-7ade6',
    authDomain: 'myinvestmentapp-7ade6.firebaseapp.com',
    storageBucket: 'myinvestmentapp-7ade6.firebasestorage.app',
    measurementId: 'G-VTQQ3XGY0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3PGkq4Wdho5u7S6VWoxjMMNTlmLwFLk',
    appId: '1:996364339289:android:81e72a9503ffaafac40948',
    messagingSenderId: '996364339289',
    projectId: 'myinvestmentapp-7ade6',
    storageBucket: 'myinvestmentapp-7ade6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx74Az5Xzt3sBezg-zxsKFR7Wgrv-X0aE',
    appId: '1:996364339289:ios:3b762cb20e6765bfc40948',
    messagingSenderId: '996364339289',
    projectId: 'myinvestmentapp-7ade6',
    storageBucket: 'myinvestmentapp-7ade6.firebasestorage.app',
    iosClientId: '996364339289-qvhtio73cn9homd61e4k9t6h0csahj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx74Az5Xzt3sBezg-zxsKFR7Wgrv-X0aE',
    appId: '1:996364339289:ios:3b762cb20e6765bfc40948',
    messagingSenderId: '996364339289',
    projectId: 'myinvestmentapp-7ade6',
    storageBucket: 'myinvestmentapp-7ade6.firebasestorage.app',
    iosClientId: '996364339289-qvhtio73cn9homd61e4k9t6h0csahj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkH0yYc0B09J90OZcCVCZo8-5sQKancHE',
    appId: '1:996364339289:web:531c62fd53b5fcc6c40948',
    messagingSenderId: '996364339289',
    projectId: 'myinvestmentapp-7ade6',
    authDomain: 'myinvestmentapp-7ade6.firebaseapp.com',
    storageBucket: 'myinvestmentapp-7ade6.firebasestorage.app',
    measurementId: 'G-2ZYVYB6C4L',
  );
}
