name: Flutter 測試

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_and_test:
    name: 分析和測試
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 設置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: 獲取依賴
        run: flutter pub get
      - name: 分析代碼
        run: flutter analyze
      - name: 運行測試
        run: flutter test --coverage
      - name: 上傳 coverage 報告
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info
      - name: 上傳覆蓋率到 Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true